version: "3.9"
services:
  ecnuvpn2socks:
    container_name: ecnu-socks
    image: ecnuvpn2socks
    ports:
      - 127.0.0.1:${SOCKS5_PORT}:1080/tcp
      - 127.0.0.1:${SOCKS5_PORT}:1080/udp
    cap_add: [NET_ADMIN]
    devices: 
      - /dev/net/tun:/dev/net/tun
    command: |-
      -vpn-username ${VPN_USER}
      -vpn-password ${VPN_PASS}
      -socks-port 1080
      -ip 127.0.0.1
    network_mode: bridge